### ISSUE TITLE
Using ASTnn on our own Dataset

### ISSUE THREAD

**Issue by shubhamrsangle** [zhangj1994/astnn#11]
Hello,

I am trying to use ASTnn for our research purposes. But, we are facing issues when we need to train model on our own dataset. As we are trying to train it entire repository code, when we are feeding code we are getting errors as we need to preprocess data according to pycparser requirement as they mention on their page.

But, we can't preprocess it as it's manual process where we have to preprocess file one by one, so we are unable to run this on repository. 

Can you please explain step by step that how can we run astnn tool on our dataset (specially when running on repository, so having lots of header files and all).

Looking forward for your reply

**Comment by ZhichaoOuyang** [comment]
I also want to know

**Comment by zhangj111** [comment]
It seems that pycparser does not support the feature you need, maybe you should do some preprocssing work before parsing it.
