### ISSUE TITLE
A bug about Code Clone Detection in file astnn/clone/pipeline.py

### ISSUE THREAD

**Issue by LINg-qwq** [zhangj1994/astnn#35]
Dear @zhangj111 ,
I tried to run Code-Clone-Detection task by using `python pipeline.py --lang c`
But an error occurred with info 'FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'datac/train/'
The correct path should be `data/c/train/` instead of `datac/train/`, which was caused by line 86 of the file astnn/clone/pipeline.py
https://github.com/zhangj111/astnn/blob/4e86c9051045943cc3455b4c2e8809225ceffa20/clone/pipeline.py#L86
To fix the bug, maybe we could change this line of code to:
`data_path = self.root+'/'+self.language+'/'`
Finally, truly thankful about your innovational paper and model.

**Comment by LINg-qwq** [comment]
Similarly, line 119 and line 157 need to be fixed.

**Comment by zhangj111** [comment]
Fixed. 
Thanks for your attention and suggestion.
Please let me know if there are any further problems.
