### ISSUE TITLE
code clone categories

### ISSUE THREAD

**Issue by marbleowo** [zhangj1994/astnn#6]
Dear writer,
        I am trying to use my own dataset on your clone code, and I see from your bcb_pair_ids.pkl that the labels are not only 0,1 but 2,3,4,5. Could you please explain that why there are more than 2 categories? Because in my perspective, the label stands for only "cloned" and "not cloned". Your help would be highly appreciated.

**Comment by zhangj111** [comment]
Hi, 
as described in our paper, there are different clone types including Type-1, Type-2, Strongly Type-3, Moderately Type-3 and Type-4, corresponding to 1-5 respectively. And 0 means "not cloned". So, if your dataset contains only 2 categories, you can refer to our dataset of [OJClone.](https://github.com/zhangj111/astnn/blob/master/clone/data/c/oj_clone_ids.pkl)  In this dataset, there are only 0 and 1 labels that meets your needs.
