### ISSUE TITLE
Shallow copy when finding best_model

### ISSUE THREAD

**Issue by jphgoodwin** [zhangj1994/astnn#8]
I could be wrong, but it looks like you're not performing a deep copy when you copy `model` to `best_model` and vice versa (train.py: line 58, 117 and 127), meaning they're both pointing at the same memory location and both get updated during optimization. In this case it would mean that you're never going to return to an earlier model state that might have had a higher accuracy, only ever the latest. I'm not sure if this is what you intended?

**Comment by jphgoodwin** [comment]
I notice that you haven't used this in the "clone" version.

**Comment by zhangj111** [comment]
Sorry for the late reply.
Yes you are right. Maybe I should use torch.save instead of assigning it to best_model. However, it seems that epoch 15 always yields the best accuracy, so there is no influence on the result.
