### ISSUE TITLE
EMBEDDING_DIM is redundant as embedding dim must match encoding dim

### ISSUE THREAD

**Issue by jphgoodwin** [zhangj1994/astnn#9]
I have noticed that the EMBEDDING_DIM variable is passed through BatchProgramClassifier() and BatchTreeEncoder() but not used when defining the dimensions of the matrix (in this case batch_current) that will be passed as input to self.W_c (line 59 of model.py). Instead the ENCODE_DIM value is used to define the shape of batch_current, and this happens to work as with the configuration you have used they both are 128. However, were you to change the EMBEDDING_DIM it would throw an error.

A potential solution to this would be to use a separate matrix to replace batch_current in the first part of traverse_mul() up to line 59 which uses self.embedding_dim (you'd need to create this variable also) instead of self.encode_dim, and then initialise batch_current in line 59.

**Comment by jphgoodwin** [comment]
If you wish me to put together these changes and submit a pull request, just let me know.

**Comment by zhangj111** [comment]
Thanks for your solution!
A pull request is welcome if you can solve this issue :)
